version: "2"
services:
  web:
    stdin_open: true
    tty: true
    image: sebp/lighttpd
    container_name: serverless
    restart: always
    volumes:
      - ./htdocs:/var/www/localhost/htdocs
      - ./etc/lighttpd:/etc/lighttpd
    ports:
      - ${WEBSERVER_PORT}:80
